name: bono
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.8.0
  go_router: ^14.7.2
  google_fonts: ^6.0.0
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
